version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gocritic
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt
